name: surrogate
channels:
  - defaults
  - conda-forge
  - pytorch
  - gpytorch

dependencies:
  - ipykernel=5.1.3
  - jupyterlab=1.1.4
  - matplotlib
  - seaborn
  - pandas=0.25.1
  - numpy
  - scikit-learn
  - pytorch
  - torchvision
  - gpytorch
  - xgboost
  - pip=19.2.3
  - python=3.7
  - python-graphviz=0.8
  - nb_conda_kernels=2.2.2

  - pip:
    - click==7.0

    - gpflow==2.0.0rc1
    - tensorflow==2.0
    - tensorflow_probability==0.8

    - pre-commit==1.18.3

    - matplotlib==3.1.1
    - nbsphinx==0.4.2
    - pytest==5.2.0
    - pytest-cov==2.7.1
    - pytest-pythonpath==0.7.3

    - sphinx==2.2.0
    - sphinx-autobuild==0.7.1
    - sphinx-rtd-theme==0.4.3
    - sphinxcontrib-bibtex==1.0.0


